server:
  port: 10008
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
    sentinel:
      transport:
        dashboard: ${SENTINEL_ADDRS:127.0.0.1:8888}
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: test-api
          uri: lb://${ADMIN_BASIC_INFO_SERVICE_HOST:test-api}
          predicates:
            - Path=/api/test/**
        - id: test
          uri: lb://${ADMIN_BASIC_INFO_SERVICE_HOST:test}
          predicates:
            - Path=/test/**
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"