server:
  port: 18888  # HTTP (Tomcat) port

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
    gateway:
      routes:
        - id: test-api
          uri: lb://${ADMIN_BASIC_INFO_SERVICE_HOST:test-api}
          predicates:
            - Path=/api/test/**
        - id: test
          uri: lb://${ADMIN_BASIC_INFO_SERVICE_HOST:test}
          predicates:
            - Path=/test/**
