@hostname=localhost
@port=8328
@Content-Type=application/json
@userName=admin
@password=public

GET http://{{hostname}}:{{port}}/test/test/1 HTTP/1.1
Content-Type: {{Content-Type}}

###
GET http://{{hostname}}:{{port}}/apply/0 HTTP/1.1
Content-Type: {{Content-Type}}
###
GET http://{{hostname}}:{{port}}/apply/listFrom?from_id=0&page=1&limit=3&sort=-time HTTP/1.1
Content-Type: {{Content-Type}}
###
GET http://{{hostname}}:{{port}}/apply/listTo?to_id=1&page=1&limit=3&sort=-time HTTP/1.1
Content-Type: {{Content-Type}}
###
POST  http://{{hostname}}:{{port}}/apply/addApply HTTP/1.1
Content-Type: {{Content-Type}}

{
    "from_id": 0,
    "to_id": 1, 
    "from_time": "2022.12.09 07:25:00",
    "to_time": "",
    "start_time": "2022.12.10 14:00:00",
    "end_time": "2022.12.10 17:00:00",
    "destination": "中关村",
    "reason": "实习",
    "comment": "",
    "status": 0
}
###
POST  http://{{hostname}}:{{port}}/apply/approval HTTP/1.1
Content-Type: {{Content-Type}}

{
    "id": 9,
    "from_id": 0,
    "to_id": 2, 
    "from_time": "2022.12.06 15:25:00",
    "to_time": "2022.12.06 15:26:00",
    "start_time": "2022.12.07 14:00:00",
    "end_time": "2022.12.07 17:00:00",
    "destination": "中关村",
    "reason": "实习",
    "comment": "好的，批准",
    "status": 0
}

###
POST  http://{{hostname}}:{{port}}/apply/deleteApply HTTP/1.1
Content-Type: {{Content-Type}}

{
    "id": 4
}
